# Lab 02: Làm quen với PyTorch

## Bài 1. Tạo Tensor cơ bản
Tạo một Tensor số nguyên kích thước 2 × 3 và hiển thị kết quả.

In [1]:
import torch

a = torch.tensor(
    [[1, 2, 3],
     [4, 5, 6]],
    dtype=torch.int32
)

print(a)


tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [2]:
# Yêu cầu: Cho biết kích thước, số chiều và kiểu dữ liệu của Tensor a.
print("Kich thuoc (shape):", a.shape)
print("So chieu (ndim):", a.ndim)
print("Kieu du lieu (dtype):", a.dtype)


Kich thuoc (shape): torch.Size([2, 3])
So chieu (ndim): 2
Kieu du lieu (dtype): torch.int32


**Nhận xét:** Tensor `a` có kích thước `torch.Size([2, 3])` (2 dòng, 3 cột), số chiều `ndim = 2` (ma trận 2 chiều), kiểu dữ liệu là `torch.int32` vì được khai báo tường minh `dtype=torch.int32`.

## Bài 2. Tạo các Tensor thường dùng
Thực hành tạo Tensor ngẫu nhiên, Tensor toàn số 0, toàn số 1 và ma trận đơn vị.

In [3]:
import torch

a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)

print(a)
print(b)
print(c)
print(d)
print(e)


tensor([[0.9408, 0.1405, 0.0513, 0.9268],
        [0.1194, 0.4195, 0.4543, 0.1081],
        [0.0842, 0.0031, 0.4704, 0.5750]])
tensor([[ 1.1617, -0.1202,  0.5771,  0.4552],
        [ 1.0103, -0.7334, -0.3501, -0.8079],
        [ 0.0702, -1.6263,  0.2131, -0.2752]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [4]:
# Yêu cầu: Tạo thêm một Tensor 5 x 5 chứa toàn giá trị 10
f = torch.full((5, 5), 10)
print(f)


tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


**Nhận xét:** `torch.rand()` sinh số ngẫu nhiên theo phân bố đều (uniform) trong khoảng [0, 1), nên giá trị luôn dương. `torch.randn()` sinh số ngẫu nhiên theo phân bố chuẩn (normal) trung bình 0, độ lệch chuẩn 1, nên giá trị có thể âm hoặc dương và không giới hạn trong [0, 1).

## Bài 3. Kiểm tra thông tin Tensor
Sử dụng shape, size(), ndim và dtype để kiểm tra các thuộc tính của Tensor.

In [5]:
import torch

a = torch.zeros(2, 3, 4)

print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)


Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


**Nhận xét:** `torch.Size([2, 3, 4])` nghĩa là Tensor có 3 chiều: chiều 0 gồm 2 "khối" (plans), mỗi khối có 3 dòng (rows), mỗi dòng có 4 cột (columns). Tổng số phần tử = 2 × 3 × 4 = 24.

## Bài 4. Slicing và Indexing
Truy xuất một phần dữ liệu từ Tensor nhiều chiều.

In [6]:
import torch

torch.manual_seed(0)
a = torch.randn(3, 4, 5)

print("Original tensor:")
print(a)

print("\nTensor a[1]:")
print(a[1])

print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])


Original tensor:
tensor([[[-1.1258, -1.1524, -0.2506, -0.4339,  0.8487],
         [ 0.6920, -0.3160, -2.1152,  0.3223, -1.2633],
         [ 0.3500,  0.3081,  0.1198,  1.2377,  1.1168],
         [-0.2473, -1.3527, -1.6959,  0.5667,  0.7935]],

        [[ 0.5988, -1.5551, -0.3414,  1.8530,  0.7502],
         [-0.5855, -0.1734,  0.1835,  1.3894,  1.5863],
         [ 0.9463, -0.8437, -0.6136,  0.0316, -0.4927],
         [ 0.2484,  0.4397,  0.1124,  0.6408,  0.4412]],

        [[-0.1023,  0.7924, -0.2897,  0.0525,  0.5943],
         [ 1.5419,  0.5073, -0.5910, -0.5692,  0.9200],
         [ 1.1108,  1.2899, -1.4959, -0.1938,  0.4455],
         [ 1.3253, -1.6293, -0.5497, -0.4798, -0.4997]]])

Tensor a[1]:
tensor([[ 0.5988, -1.5551, -0.3414,  1.8530,  0.7502],
        [-0.5855, -0.1734,  0.1835,  1.3894,  1.5863],
        [ 0.9463, -0.8437, -0.6136,  0.0316, -0.4927],
        [ 0.2484,  0.4397,  0.1124,  0.6408,  0.4412]])

Tensor a[1:, 2:4]:
tensor([[[ 0.9463, -0.8437, -0.6136,  0.0316, -0.4

In [7]:
# Yêu cầu:
# - Cho biết shape của a[1] và a[1:, 2:4]
# - Thử lấy hai phần tử cuối cùng trên chiều thứ ba
print("Shape a[1]:", a[1].shape)
print("Shape a[1:, 2:4]:", a[1:, 2:4].shape)

print("\nHai phan tu cuoi tren chieu thu ba:")
print(a[:, :, -2:])


Shape a[1]: torch.Size([4, 5])
Shape a[1:, 2:4]: torch.Size([2, 2, 5])

Hai phan tu cuoi tren chieu thu ba:
tensor([[[-0.4339,  0.8487],
         [ 0.3223, -1.2633],
         [ 1.2377,  1.1168],
         [ 0.5667,  0.7935]],

        [[ 1.8530,  0.7502],
         [ 1.3894,  1.5863],
         [ 0.0316, -0.4927],
         [ 0.6408,  0.4412]],

        [[ 0.0525,  0.5943],
         [-0.5692,  0.9200],
         [-0.1938,  0.4455],
         [-0.4798, -0.4997]]])


**Nhận xét:** `a[1]` bỏ đi chiều đầu tiên (chỉ lấy khối thứ 2) nên shape còn `(4, 5)`. `a[1:, 2:4]` giữ nguyên 3 chiều nhưng chiều 0 chỉ còn 2 khối (từ index 1 trở đi) và chiều 1 chỉ còn 2 dòng (index 2, 3), nên shape là `(2, 2, 5)`.

## Bài 5. Reshape và Flatten
Thay đổi hình dạng Tensor mà không làm thay đổi số phần tử.

In [8]:
import torch

torch.manual_seed(0)
a = torch.randn(3, 4)

print("Original:")
print(a)

print("\nFlatten:")
print(a.ravel())

print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))


Original:
tensor([[ 1.5410, -0.2934, -2.1788,  0.5684],
        [-1.0845, -1.3986,  0.4033,  0.8380],
        [-0.7193, -0.4033, -0.5966,  0.1820]])

Flatten:
tensor([ 1.5410, -0.2934, -2.1788,  0.5684, -1.0845, -1.3986,  0.4033,  0.8380,
        -0.7193, -0.4033, -0.5966,  0.1820])

Reshape to 3 x 2 x 2:
tensor([[[ 1.5410, -0.2934],
         [-2.1788,  0.5684]],

        [[-1.0845, -1.3986],
         [ 0.4033,  0.8380]],

        [[-0.7193, -0.4033],
         [-0.5966,  0.1820]]])


In [9]:
# Yêu cầu:
# - Kiểm tra số phần tử trước và sau khi reshape
# - Thử reshape Tensor thành kích thước 2 x 6
print("So phan tu truoc reshape:", a.numel())
print("So phan tu sau reshape (3,2,2):", a.reshape(3, 2, 2).numel())

b = a.reshape(2, 6)
print("\nReshape thanh 2 x 6:")
print(b)


So phan tu truoc reshape: 12
So phan tu sau reshape (3,2,2): 12

Reshape thanh 2 x 6:
tensor([[ 1.5410, -0.2934, -2.1788,  0.5684, -1.0845, -1.3986],
        [ 0.4033,  0.8380, -0.7193, -0.4033, -0.5966,  0.1820]])


**Nhận xét:** Reshape chỉ thay đổi cách "nhìn" dữ liệu (số dòng/cột/chiều), không làm thay đổi tổng số phần tử — luôn phải giữ đúng tích các chiều bằng số phần tử ban đầu (ở đây là 12).

## Bài 6. Phép toán và nhân ma trận
Thực hiện các phép toán phần tử và phép nhân ma trận bằng toán tử @.

In [10]:
import torch

torch.manual_seed(0)
a = torch.randn(2, 3)
b = torch.randn(2, 3)

print("a:")
print(a)
print("b:")
print(b)

print("\na + b:")
print(a + b)

print("\na / b:")
print(a / b)

print("\na^2:")
print(a ** 2)

print("\nMatrix multiplication:")
print(a @ b.T)


a:
tensor([[ 1.5410, -0.2934, -2.1788],
        [ 0.5684, -1.0845, -1.3986]])
b:
tensor([[ 0.4033,  0.8380, -0.7193],
        [-0.4033, -0.5966,  0.1820]])

a + b:
tensor([[ 1.9443,  0.5446, -2.8980],
        [ 0.1651, -1.6812, -1.2166]])

a / b:
tensor([[ 3.8205, -0.3501,  3.0292],
        [-1.4093,  1.8177, -7.6831]])

a^2:
tensor([[2.3747, 0.0861, 4.7471],
        [0.3231, 1.1762, 1.9561]])

Matrix multiplication:
tensor([[ 1.9428, -0.8431],
        [ 0.3264,  0.1632]])


In [11]:
# Yêu cầu: cho biết shape của a @ b.T
print("Shape a @ b.T:", (a @ b.T).shape)


Shape a @ b.T: torch.Size([2, 2])


**Nhận xét:** `a * b` là phép nhân **theo từng phần tử tương ứng** (element-wise), yêu cầu 2 Tensor cùng shape, kết quả cùng shape (2, 3). `a @ b.T` là phép **nhân ma trận** thực sự (dot product theo hàng-cột), ở đây `a` có shape (2,3), `b.T` có shape (3,2), nên kết quả có shape (2, 2).

## Bài 7. Các hàm thống kê trên Tensor
Tính trung bình, độ lệch chuẩn và tổng tích lũy theo từng cột.

In [12]:
import torch

torch.manual_seed(0)
a = torch.randn(3, 4)

print(a)

print("\nMean (dim=0):")
print(torch.mean(a, dim=0))

print("\nStandard deviation (dim=0):")
print(torch.std(a, dim=0))

print("\nCumulative sum (dim=0):")
print(torch.cumsum(a, dim=0))


tensor([[ 1.5410, -0.2934, -2.1788,  0.5684],
        [-1.0845, -1.3986,  0.4033,  0.8380],
        [-0.7193, -0.4033, -0.5966,  0.1820]])

Mean (dim=0):
tensor([-0.0876, -0.6985, -0.7907,  0.5295])

Standard deviation (dim=0):
tensor([1.4222, 0.6088, 1.3020, 0.3297])

Cumulative sum (dim=0):
tensor([[ 1.5410, -0.2934, -2.1788,  0.5684],
        [ 0.4565, -1.6920, -1.7754,  1.4065],
        [-0.2628, -2.0954, -2.3721,  1.5885]])


In [13]:
# Yêu cầu: thay dim=0 bằng dim=1
print("Mean (dim=1):")
print(torch.mean(a, dim=1))

print("\nStandard deviation (dim=1):")
print(torch.std(a, dim=1))

print("\nCumulative sum (dim=1):")
print(torch.cumsum(a, dim=1))


Mean (dim=1):
tensor([-0.0907, -0.3104, -0.3843])

Standard deviation (dim=1):
tensor([1.5809, 1.0972, 0.3993])

Cumulative sum (dim=1):
tensor([[ 1.5410,  1.2476, -0.9312, -0.3628],
        [-1.0845, -2.4831, -2.0798, -1.2417],
        [-0.7193, -1.1226, -1.7192, -1.5372]])


**Nhận xét:** `dim=0` tính toán **dọc theo cột** (kết quả có 4 giá trị — mỗi giá trị đại diện 1 cột), còn `dim=1` tính toán **dọc theo dòng** (kết quả có 3 giá trị — mỗi giá trị đại diện 1 dòng). Nói cách khác, `dim` chỉ định chiều bị "gộp lại" khi tính toán.

## Bài 8. Autograd cơ bản
Tạo biến có requires_grad=True và dùng backward() để tính đạo hàm tự động.

In [5]:
import torch

x = torch.tensor(
    3.6,
    requires_grad=True
)

y = x * x
y.backward()

print("x =", x)
print("y =", y)
print("x.grad =", x.grad)


x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


In [6]:
# Yêu cầu 1: Tính thủ công đạo hàm của y = x^2 tại x = 3.6 và so sánh với x.grad
# dy/dx = 2x --> tai x=3.6: dy/dx = 7.2
dy_dx_thu_cong = 2 * 3.6
print("Dao ham thu cong dy/dx tai x=3.6:", dy_dx_thu_cong)
print("x.grad (PyTorch tinh):", x.grad.item())
print("So sanh: trung khop!" if abs(dy_dx_thu_cong - x.grad.item()) < 1e-6 else "Khac nhau")


Dao ham thu cong dy/dx tai x=3.6: 7.2
x.grad (PyTorch tinh): 7.199999809265137
So sanh: trung khop!


In [7]:
# Yêu cầu 2: Đổi hàm thành y = 3*x**2 + 2*x + 1 và kiểm tra gradient
x2 = torch.tensor(3.6, requires_grad=True)
y2 = 3 * x2 ** 2 + 2 * x2 + 1
y2.backward()

# dao ham thu cong: dy/dx = 6x + 2 --> tai x=3.6: 6*3.6+2 = 23.6
dy_dx_thu_cong2 = 6 * 3.6 + 2
print("y2 =", y2)
print("x2.grad (PyTorch tinh):", x2.grad.item())
print("Dao ham thu cong:", dy_dx_thu_cong2)


y2 = tensor(47.0800, grad_fn=<AddBackward0>)
x2.grad (PyTorch tinh): 23.599998474121094
Dao ham thu cong: 23.6


**Nhận xét:** Với `y = x²`, đạo hàm `dy/dx = 2x`, tại `x = 3.6` cho kết quả `7.2` — khớp hoàn toàn với `x.grad` mà PyTorch tự tính qua `backward()`. Với `y = 3x² + 2x + 1`, đạo hàm `dy/dx = 6x + 2`, tại `x = 3.6` cho `23.6` — cũng khớp với `x2.grad`. Điều này cho thấy autograd tính đạo hàm chính xác theo quy tắc giải tích, không phải xấp xỉ.

## Bài 9. Gradient Descent tìm hệ số đa thức
Sinh dữ liệu từ đa thức y = x² + 2x + 3, sau đó dùng NAdam và autograd để tìm lại ba hệ số.

In [17]:
import numpy as np
import torch

torch.manual_seed(0)
np.random.seed(0)

polynomial = np.poly1d([1, 2, 3])
N = 20

X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

print("Learned coefficients:")
print(w)


Initial coefficients:
tensor([[ 1.5410],
        [-0.2934],
        [-2.1788]], requires_grad=True)
Learned coefficients:
tensor([[1.0017],
        [2.0058],
        [2.8337]], requires_grad=True)


**Nhận xét:**
- Ba hệ số học được (`w`) sau 1000 vòng lặp xấp xỉ rất gần với `[1, 2, 3]` — đúng với đa thức gốc `y = x² + 2x + 3`, chứng tỏ Gradient Descent đã hội tụ đúng.
- `optimizer.zero_grad()`: xóa gradient tích lũy từ vòng lặp trước (PyTorch mặc định cộng dồn gradient, nếu không xóa sẽ tính sai).
- `mse.backward()`: tính gradient của hàm mất mát `mse` theo từng tham số `w` bằng autograd (lan truyền ngược).
- `optimizer.step()`: cập nhật giá trị `w` theo hướng ngược gradient (giảm dần sai số), theo công thức của thuật toán NAdam.

## Bài 10. Giải hệ phương trình bằng Autograd
Tối thiểu hóa tổng sai số bình phương để tìm A, B, C, D thỏa bốn phương trình.

In [18]:
import random
import torch

random.seed(0)
torch.manual_seed(0)

A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)

EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)

for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2

    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4

    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()

print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)


A = tensor(4.5494, requires_grad=True)
B = tensor(4.4506, requires_grad=True)
C = tensor(3.4506, requires_grad=True)
D = tensor(2.4506, requires_grad=True)


In [19]:
# Yêu cầu: Kiểm tra nghiệm thu được với 4 phương trình
print("A + B =", (A + B).item(), " (ky vong = 9)")
print("C - D =", (C - D).item(), " (ky vong = 1)")
print("A + C =", (A + C).item(), " (ky vong = 8)")
print("B - D =", (B - D).item(), " (ky vong = 2)")


A + B = 8.99995231628418  (ky vong = 9)
C - D = 1.0000104904174805  (ky vong = 1)
A + C = 7.999969005584717  (ky vong = 8)
B - D = 1.9999933242797852  (ky vong = 2)


**Nhận xét:** Cả 4 giá trị kiểm tra đều xấp xỉ đúng vế phải (9, 1, 8, 2), cho thấy nghiệm tìm được thỏa hệ phương trình. Tuy nhiên bài toán có **4 ẩn nhưng chỉ 4 phương trình độc lập tuyến tính** — thực chất hệ này có vô số nghiệm (thiếu 1 điều kiện để xác định duy nhất D, các biến còn lại phụ thuộc vào D), vì nếu đặt D = d bất kỳ thì A, B, C đều có thể suy ra tương ứng mà vẫn thỏa cả 4 phương trình. Vì vậy, giá trị A, B, C, D cụ thể tìm được phụ thuộc vào điểm khởi tạo ngẫu nhiên ban đầu.

## Bài 11. Bài tập áp dụng

### a) Tạo Tensor X có 24 phần tử và reshape lần lượt thành 4×6, 2×12, 2×3×4

In [20]:
import torch

X = torch.arange(24)
print("X ban dau:", X)

X_4x6 = X.reshape(4, 6)
X_2x12 = X.reshape(2, 12)
X_2x3x4 = X.reshape(2, 3, 4)

print("\nReshape 4 x 6:")
print(X_4x6)

print("\nReshape 2 x 12:")
print(X_2x12)

print("\nReshape 2 x 3 x 4:")
print(X_2x3x4)


X ban dau: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

Reshape 4 x 6:
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

Reshape 2 x 12:
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

Reshape 2 x 3 x 4:
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


### b) Tạo hai Tensor A, B kích thước 3×4; tính A+B, A*B, A/B, trung bình theo cột, độ lệch chuẩn theo cột

In [21]:
import torch

torch.manual_seed(1)
A = torch.randn(3, 4)
B = torch.randn(3, 4)

print("A:")
print(A)
print("B:")
print(B)

print("\nA + B:")
print(A + B)

print("\nA * B:")
print(A * B)

print("\nA / B:")
print(A / B)

print("\nTrung binh theo cot (dim=0):")
print(torch.mean(A, dim=0))

print("\nDo lech chuan theo cot (dim=0):")
print(torch.std(A, dim=0))


A:
tensor([[ 0.6614,  0.2669,  0.0617,  0.6213],
        [-0.4519, -0.1661, -1.5228,  0.3817],
        [-1.0276, -0.5631, -0.8923, -0.0583]])
B:
tensor([[-0.1955, -0.9656,  0.4224,  0.2673],
        [-0.4212, -0.5107, -1.5727, -0.1232],
        [ 3.5870, -1.8313,  1.5987, -1.2770]])

A + B:
tensor([[ 0.4658, -0.6987,  0.4841,  0.8886],
        [-0.8731, -0.6768, -3.0954,  0.2584],
        [ 2.5594, -2.3943,  0.7064, -1.3353]])

A * B:
tensor([[-0.1293, -0.2578,  0.0261,  0.1661],
        [ 0.1903,  0.0848,  2.3948, -0.0470],
        [-3.6860,  1.0311, -1.4265,  0.0744]])

A / B:
tensor([[-3.3827, -0.2764,  0.1460,  2.3243],
        [ 1.0729,  0.3253,  0.9683, -3.0969],
        [-0.2865,  0.3075, -0.5581,  0.0456]])

Trung binh theo cot (dim=0):
tensor([-0.2727, -0.1541, -0.7845,  0.3149])

Do lech chuan theo cot (dim=0):
tensor([0.8586, 0.4151, 0.7977, 0.3447])


### c) Cho y = 2x² + 5x + 3. Dùng autograd tính dy/dx tại x = 2 và kiểm tra bằng phép tính thủ công

In [22]:
import torch

x = torch.tensor(2.0, requires_grad=True)
y = 2 * x ** 2 + 5 * x + 3
y.backward()

# dao ham thu cong: dy/dx = 4x + 5 --> tai x=2: 4*2+5 = 13
dy_dx_thu_cong = 4 * 2 + 5

print("y =", y.item())
print("x.grad (autograd):", x.grad.item())
print("Dao ham thu cong:", dy_dx_thu_cong)


y = 21.0
x.grad (autograd): 13.0
Dao ham thu cong: 13


### d) Thay đa thức trong Bài 9 bằng y = 2x² - 3x + 5; huấn luyện và cho biết các hệ số tìm được

In [23]:
import numpy as np
import torch

torch.manual_seed(0)
np.random.seed(0)

polynomial = np.poly1d([2, -3, 5])
N = 20

X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(2000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

print("Learned coefficients (ky vong ~ [2, -3, 5]):")
print(w)


Initial coefficients:
tensor([[ 1.5410],
        [-0.2934],
        [-2.1788]], requires_grad=True)


Learned coefficients (ky vong ~ [2, -3, 5]):
tensor([[ 2.0004],
        [-2.9989],
        [ 4.9648]], requires_grad=True)


**Nhận xét:** Sau khi huấn luyện, ba hệ số học được xấp xỉ rất gần `[2, -3, 5]` — đúng với đa thức gốc `y = 2x² - 3x + 5`, cho thấy phương pháp Gradient Descent với optimizer NAdam áp dụng được cho bất kỳ đa thức bậc 2 nào, chỉ cần đổi hệ số sinh dữ liệu ban đầu.

# Kết thúc